  -- \set doc `cat jsonfile`  then use  json_to_recordset(:'doc')


create table gris
as select * from json_to_recordset('[
    {
        "nr": 8936603,
        "Artikelid": 1000155,
        "Varnummer": 89366,
        "Namn": "Midas Golden Pilsner",
        "Namn2": "",
        "Prisinklmoms": 26.7,
        "Volymiml": 330,
        "PrisPerLiter": 80.91,
        "Saljstart": "2015-09-01",
        "Utgått": 0,
        "Varugrupp": "Öl",
        "Typ": "Ljus lager",
        "Stil": "Modern stil",
        "Forpackning": "Flaska",
        "Forslutning": "",
        "Ursprung": "",
        "Ursprunglandnamn": "Sverige",
        "Producent": "Imperiebryggeriet AB",
        "Leverantor": "Imperiebryggeriet  AB",
        "Argang": "",
        "Provadargang": "",
        "Alkoholhalt": "4.90%",
        "Sortiment": "BS",
        "SortimentText": "Övrigt sortiment",
        "Ekologisk": 0,
        "Etiskt": 0,
        "Koscher": 0
    },
    {
        "nr": 8983803,
        "Artikelid": 1000432,
        "Varnummer": 89838,
        "Namn": "Schlappeseppel Specialität",
        "Namn2": "",
        "Prisinklmoms": 27.1,
        "Volymiml": 330,
        "PrisPerLiter": 82.12,
        "Saljstart": "2015-09-01",
        "Utgått": 0,
        "Varugrupp": "Öl",
        "Typ": "Mellanmörk lager",
        "Stil": "Märzen och wienerstil",
        "Forpackning": "Flaska",
        "Forslutning": "",
        "Ursprung": "",
        "Ursprunglandnamn": "Tyskland",
        "Producent": "Schlappeseppel GmbH",
        "Leverantor": "Dryckesboden Sverige AB",
        "Argang": "",
        "Provadargang": "",
        "Alkoholhalt": "5.60%",
        "Sortiment": "BS",
        "SortimentText": "Övrigt sortiment",
        "Ekologisk": 0,
        "Etiskt": 0,
        "Koscher": 0
    }
]') as s(
    nr integer,
    Artikelid integer,
    Varnummer integer,
    Namn text,
    Namn2 text,
    Prisinklmoms single,
    Volymiml integer,
    PrisPerLiter single,
    Saljstart date,
    Utgått integer,
    Varugrupp text,
    Typ text,
    Stil text,
    Forpackning text,
    Forslutning text,
    Ursprung text,
    Ursprunglandnamn text,
    Producent text,
    Leverantor text,
    Argang integer,
    Provadargang integer,
    Alkoholhalt text,
    Sortiment text,
    SortimentText text,
    Ekologisk integer,
    Etiskt integer,
    Koscher integer,
    );
