\set doc `cat ./beersFS_both_API1.json`
-- then use  json_to_recordset(:'doc')

-- create table mytable as select * from json_to_recordset('[...]') as s(a integer, b text);
create table 49beers
as select * from json_to_recordset(:'doc') as s(
    "nr" integer,
    "Artikelid" integer,
    "Varnummer" integer,
    "Namn" text,
    "Namn2" text,
    "Prisinklmoms" numeric,
    "Volymiml" integer,
    "PrisPerLiter" numeric,
    "Saljstart" date,
    "Utgått" integer,
    "Varugrupp" text,
    "Typ" text,
    "Stil" text,
    "Forpackning" text,
    "Forslutning" text,
    "Ursprung" text,
    "Ursprunglandnamn" text,
    "Producent" text,
    "Leverantor" text,
    "Argang" text,
    "Provadargang" text,
    "Alkoholhalt" text,
    "Sortiment" text,
    "SortimentText" text,
    "Ekologisk" integer,
    "Etiskt" integer,
    "Koscher" integer,
    "bid" integer,
    "beer_name" text,
    "beer_label" text,
    "beer_label_hd" text,
    "beer_abv" numeric,
    "beer_ibu" integer,
    "beer_description" text,
    "beer_style" text,
    "is_in_production" integer,
    "beer_slug" text,
    "is_homebrew" integer,
    "created_at" text,
    "rating_count" integer,
    "rating_score" numeric,
    "stats" text,
    "brewery" text,
    "auth_rating" integer,
    "wish_list" text,
    "weighted_rating_score" numeric,
    "vintages" text,
    )